# site name
prefixName: こんにゃく1匹
siteName: 一只蒟蒻仔
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://uncleacc.github.io
description: Enrich-everyday
cdn: https://cdn.jsdelivr.net/gh/uncleacc/cdn@1.4
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎大家浏览我的博客
lazyloadImg: https://cdn.jsdelivr.net/gh/uncleacc/cdn@1.4/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    算法: {path: /categories/算法/, fa: fa-code }, 
    题目: {path: /categories/题目/, fa: fa-balance-scale }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    记录: {path: /categories/记录/, fa: fa-commenting-o },
    技术: {path: /categories/技术/, fa: fa-book },
  } }
  清单: { path: /, fa: fa-list-ul faa-vertical, submenus: { 
    转载: {path: /tags/转载/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    # 图集: {path: /tags/图集/, fa: fa-photo }
  } }
  说说: {path: /shuoshuo/, fa: fa-commenting-o fa-commenting }
  标签: {path: /tags/, fa: fa-tag }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/1.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/2.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/3.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/4.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/5.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/6.webp
  - https://cdn.jsdelivr.net/gh/uncleacc/Img/cover/7.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/525424930, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: https://www.hojun.cn/, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}
  
# your site build time or founded date
siteBuildingTime: 03/29/2020

#social  url, img PC端配置
social:
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  github: {url: http://github.com/uncleacc, img: /img/social/github.png}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=601162956&site=qq&menu=yes, img: /img/social/qq.png}
  # qq: {url: /#, qrcode: /img/custom/qq.jpg, img: /img/social/qq.png}
  # wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  csdn: {url: https://blog.csdn.net/AGNING, img: /img/social/csdn.png}
  bilibili: {url: https://space.bilibili.com/525424930, img: /img/social/bilibili.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/uncleacc, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=601162956&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanSQ.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# Valine
valine: true
v_appId: OzumpR4mNEQHal4gBO3BRxj6-gzGzoHsz
v_appKey: VfTovKhM6MXIwyAbfAogWSLn

# 是否开启字数统计
#不需要使用，直接设置值为false，或注释掉
word_count: true
